### ISSUE TITLE
A Pure Lyric Display?

### ISSUE THREAD

**Issue by ghost** [wayou/selected#4]
你好，我是一名在校研究生，因为要考托福，所以自己简单实现了一个被托福单词的网站，[TOEFL VOCABULARIES](http://happyjohann.esy.es/toefl/), [Github代码](https://github.com/happyjohann/learn-vocabulary-with-lrc).  因为是个php, js, css3, html5的初学者，所以代码写的实在太烂，功能也并不完善。

因为想到了音频和lyric的同步滚动可能更有利于记忆，所以找到你写的这个网站，觉得挺符合我的需求的。但是

能请教如何实现类似于 [Google Hot Search Trends Visualize](https://www.google.com/trends/hottrends/visualize?pn=p1) 界面的简介歌词显示吗？

另外，在搜索的过程中，发现这个网站[mraiur/music-player](https://github.com/mraiur/music-player)关于音频文件的组织挺好的，能够借鉴过来么？（我发现在你的这个repo中又一个json文件时专门记录歌曲名称作者等的，需要手工维护么？还是代码自动提取处理的？）

由于你的repo有点儿大，所以代码还没有clone完……

**Comment by wayou** [comment]
hi,
- 你是指类似卡拉OK式细化到单个字符的歌词同步？这个木有研究过
- json数据是手动维护的，因为没有后端所以无法自动跑，当然你可以用后端也可以写脚本
- 歌曲多所以大，如果你只是看代码的话只需要把js拿出来就可啦

**Comment by ghost** [comment]
也不是指卡拉OK一样，只是讲歌词显示的界面变得更纯粹一点儿，每一次只显示一句歌词，界面和 [Google Hot Search Trends Visualize](https://www.google.com/trends/hottrends/visualize?pn=p1)类似，也就是 尽量每次只显示出一句歌词，可以将注意力集中在一句话，而不是看得到很多句歌词，当前歌词加亮。

这样对于背单词效果会好很多。

歌曲多慢的原因发现了，但是发现Git并不能选择性的git clone，一clone就是全部的 😢

大神有时间实现个类似于 [Google Hot Search Trends Visualize](https://www.google.com/trends/hottrends/visualize?pn=p1) 的界面么？
实在是自己对CSS和JS不是太熟悉。

[Google Hot Search Trends Visualize](https://www.google.com/trends/hottrends/visualize?pn=p1) 的静态代码在我的repo中有，[happyjohann/learn-vocabulary-with-lrc](https://github.com/happyjohann/learn-vocabulary-with-lrc/tree/master/assets)。

简单来说，我其实就是想有一个帮助被单词的music player。然后发现你的这个项目所有的功能都有了，然而界面并不能太适合讲注意力集中到 正在播放的单词。
由于对css和js实在不是太熟悉，然后大神又用了貌似并不简单的语法，css3和比较高阶的js，所以折腾了半天也没有搞定，所以来求助了，求帮忙Y(^_^)Y
